name: Deploy to Github Pages

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.1
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: nikorablin.io
          publish_dir: ./out
